### ISSUE TITLE
<leader>o in vim doesn't open browser

### ISSUE THREAD

**Issue by adamyonk** [danchoi/goog#1]
When I hit `<leader>o` in vim, it just shows the following in the status line:

`:call <SNR>26_open_href_under_cursor(0)`

**Comment by danchoi** [comment]
What OS are you using?

On Thu, May 24, 2012 at 09:38 AM, Adam Jahnke reply@reply.github.com wrote:

> from: Adam Jahnke reply@reply.github.com
> date: Thu, May 24 06:38 AM -07:00 2012
> to: Daniel Choi dhchoi@gmail.com
> subject: [goog] <leader>o in vim doesn't open browser (#1)
> 
> When I hit <leader>o in vim, it just shows the following in the status line:
> 
> `:call <SNR>26_open_href_under_cursor(0)`
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/danchoi/goog/issues/1

---

Sent from vmail
https://github.com/danchoi/vmail

**Comment by adamyonk** [comment]
OS X 10.7.4.

**Comment by danchoi** [comment]
can you type `:map <leader>o` in vim normal mode and paste the output here?

**Comment by adamyonk** [comment]
`,o          * :call <SNR>54_open_href(0)<CR><Space>`

**Comment by danchoi** [comment]
Are you using macvim or regular vim?

**Comment by adamyonk** [comment]
Regular vim.

**Comment by danchoi** [comment]
Then you use <leader>o, does the cursor move to the 2nd character of the next link?

**Comment by danchoi** [comment]
Also try typing `:!open http://yahoo.com` in Vim and see if that opens the webpage in your browser

**Comment by adamyonk** [comment]
I took a screen recording: http://cl.ly/Grlm

Also, `:!open <url>` works as expected in Vim.

**Comment by danchoi** [comment]
OK I figured it out. You're on an older version. Please update the gem and run `goog --install`
